import { Inter } from "next/font/google"; // Replace Geist with Inter
import "./globals.css";
import AuthProvider from "./component/Authprovider";
import ChatbotLauncher from "./component/ChatbotLauncher";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          {children}
          <ChatbotLauncher />
        </AuthProvider>
      </body>
    </html>
  );
}
